// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Playstate struct {
	UserID       uuid.UUID      `json:"user_id"`
	BookChapter  sql.NullString `json:"book_chapter"`
	SeekPosition sql.NullInt32  `json:"seek_position"`
}
