// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const newSeekPosition = `-- name: NewSeekPosition :exec
INSERT into PLAYSTATE(user_id, book_chapter, seek_position) values($1,$2, $3)
`

type NewSeekPositionParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	BookChapter  sql.NullString `json:"book_chapter"`
	SeekPosition sql.NullInt32  `json:"seek_position"`
}

func (q *Queries) NewSeekPosition(ctx context.Context, arg NewSeekPositionParams) error {
	_, err := q.exec(ctx, q.newSeekPositionStmt, newSeekPosition, arg.UserID, arg.BookChapter, arg.SeekPosition)
	return err
}

const updateSeekPosition = `-- name: UpdateSeekPosition :exec
UPDATE PLAYSTATE SET seek_position=$1 where user_id=$2 and book_chapter=$3
`

type UpdateSeekPositionParams struct {
	SeekPosition sql.NullInt32  `json:"seek_position"`
	UserID       uuid.UUID      `json:"user_id"`
	BookChapter  sql.NullString `json:"book_chapter"`
}

func (q *Queries) UpdateSeekPosition(ctx context.Context, arg UpdateSeekPositionParams) error {
	_, err := q.exec(ctx, q.updateSeekPositionStmt, updateSeekPosition, arg.SeekPosition, arg.UserID, arg.BookChapter)
	return err
}
